=== kaarriet/Assignment4/Hotels.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns="http://github.com/kaarriet/Assignment4/"
            targetNamespace="http://github.com/kaarriet/Assignment4/"
            elementFormDefault="qualified" attributeFormDefault="unqualified">
    
    <xsd:element name="Hotels" type="HotelsType"/>
    
    <xsd:complexType name="HotelsType">
        <xsd:sequence>
            <xsd:element name="Hotel" type="HotelType" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="HotelType">
        <xsd:sequence>
            <xsd:element name="Name" type="xsd:string"/>
            <xsd:element name="Address" type="AddressType"/>
            <xsd:element name="Phone" type="PhoneType" minOccurs="1" maxOccurs="unbounded"/>
            <xsd:element name="Rating" type="xsd:decimal" minOccurs="0"/>
        </xsd:sequence>
        <xsd:attribute name="NearbyAirport" type="xsd:string" use="optional"/>
    </xsd:complexType>
    
    <xsd:complexType name="AddressType">
        <xsd:sequence>
            <xsd:element name="Number" type="xsd:int"/>
            <xsd:element name="Street" type="xsd:string"/>
            <xsd:element name="City" type="xsd:string"/>
            <xsd:element name="State" type="xsd:string"/>
            <xsd:element name="Zip" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="PhoneType">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="type" type="xsd:string" use="optional"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>
</xsd:schema>

=== kaarriet/Assignment4/HotelsErrors.xml
<?xml version="1.0" encoding="UTF-8"?>
<Hotel xmlns="http://github.com/kaarriet/Assignment4/"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://github.com/kaarriet/Assignment4/ Hotels.xsd">
    
    <Hotel>
        <Name>Westin</Name>
        <Address>
            <Number>11</Number>
            <Street>E 7th St</Street>
            <City>Tempe</City>
            <State>AZ</State>
            <Zip>85281</Zip>
        </Address>
        <Rating>4.2</Rating>
    </Hotel>

    <Hotel>
        <Name>Marriott</Name>
        <Name>DuplicateName</Name> <!-- Intentional error: duplicate Name elements -->
        <Address>
            <Number>123</Number>
            <Street>Main St</Street>
            <City>Phoenix</City>
            <State>AZ</State>
            <!-- Missing closing tag for Zip element -->
            <Zip>85004
        </Address>
        <Phone>602-555-1234</Phone>
    </Hotel>

</Hotel>

=== kaarriet/Assignment4/Hotels.xml
<?xml version="1.0" encoding="UTF-8"?>
<Hotels xmlns="http://github.com/kaarriet/Assignment4/"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://github.com/kaarriet/Assignment4/ Hotels.xsd">
    
    <Hotel NearbyAirport="Sky Harbor">
        <Name>Westin</Name>
        <Address>
            <Number>11</Number>
            <Street>E 7th St</Street>
            <City>Tempe</City>
            <State>AZ</State>
            <Zip>85281</Zip>
        </Address>
        <Phone type="primary">480-968-8885</Phone>
        <Phone type="tollfree">800-937-8461</Phone>
        <Rating>4.2</Rating>
    </Hotel>

    <Hotel NearbyAirport="Phoenix Airport">
        <Name>Marriott</Name>
        <Address>
            <Number>123</Number>
            <Street>Main St</Street>
            <City>Phoenix</City>
            <State>AZ</State>
            <Zip>85004</Zip>
        </Address>
        <Phone>602-555-1234</Phone>
    </Hotel>

    <!-- Add more hotel entries here, following the same structure -->
</Hotels>
